### ISSUE TITLE
Add in between phase between uploading page and studying notecards

### ISSUE THREAD

**Issue by Michielu** [Don-V/notecard-maker#5]
Have a page that displays all the notecards the parser created with all of them currently selected. Give the use an option to unclick notecards that they don't want to study at the moment(or if our parser picked up something the user wasn't anticipating)

**Comment by amupitan** [comment]
Can the in between page be where they see all their notes. Then, when they try to study note-cards, they can select what note/notes and what note-cards to study @Michielu
