### ISSUE TITLE
Have a users page (after log in)

### ISSUE THREAD

**Issue by Michielu** [Don-V/notecard-maker#9]
When a user signs in, allow the user to visit their "users"  page. This should contain all their previous notecards they have uploaded.

*have an option to delete notecards/decks of notecards.

**Comment by amupitan** [comment]
Also change url after users login

**Comment by amupitan** [comment]
This is now done in other pages and "have an option to delete notecards/decks of notecards." is now issue #15 .
Closed in 87d41e2
